name: mlops_final
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.0=hbb29018_2
  - comm=0.2.3=py310h06a4308_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - dav1d=1.2.1=hd590300_0
  - decorator=5.2.1=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=6.1.1=hecf7045_5
  - filelock=3.20.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.2=h59595ed_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=pyhcf101f3_1
  - jpeg=9e=h0b41bf4_3
  - jupyter_client=8.8.0=py310h06a4308_0
  - jupyter_core=5.9.1=py310h06a4308_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libarchive=3.8.2=h3ec8f01_0
  - libavif=1.3.0=h3539ee5_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libdeflate=1.22=hb9d3cd8_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.84.0=h2ff4ddf_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=5_h47877c9_openblas
  - libnsl=2.0.0=h5eee18b_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.6.1=h280c20c_0
  - libpng=1.6.54=h421ea60_0
  - libprotobuf=5.28.3=h6128344_1
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.1=h029b1ac_0
  - libtorch=2.5.1=cpu_generic_h90be84d_13
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.15.2=hecca717_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - networkx=3.4.2=pyh267e887_2
  - nomkl=1.0=h5ca1d4c_0
  - numpy=2.2.6=py310hefbff90_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=py310h06a4308_1
  - parso=0.8.5=py310h06a4308_0
  - pcre2=10.44=hc749103_2
  - pexpect=4.9.0=py310h06a4308_1
  - pillow=12.0.0=py310h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pygments=2.19.2=py310h06a4308_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=cpu_generic_py310_h1535f1e_13
  - pyzmq=27.1.0=py310hcf8288c_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sleef=3.9.0=ha0421bc_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=py310h06a4308_0
  - sympy=1.14.0=pyh2585a3b_105
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=2.5.1=py310h1128e8f_0
  - torchvision=0.20.1=cpu_py310h1c79344_2
  - tornado=6.5.4=py310h47b2149_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - debugpy==1.8.19
      - defusedxml==0.7.1
      - exceptiongroup==1.3.1
      - fastjsonschema==2.21.2
      - flatbuffers==25.12.19
      - fqdn==1.5.1
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - ipykernel==7.1.0
      - ipython==8.38.0
      - isoduration==20.11.0
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-mathjax==0.2.6
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.2
      - jupyterlab-git==0.51.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - keras==3.12.0
      - lark==1.3.1
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - namex==0.1.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbdime==4.0.3
      - nbformat==5.10.4
      - notebook-shim==0.2.4
      - opt-einsum==3.4.0
      - optree==0.18.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - platformdirs==4.5.1
      - prometheus-client==0.24.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pycparser==2.23
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - send2trash==2.1.0
      - smmap==5.0.2
      - soupsieve==2.8.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.3.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.4.0
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.5
      - wrapt==2.0.1
prefix: /home/guilherme/miniconda3/envs/mlops_final
